What are iterators
What are iterables
How for loop works in Python?
Making your own for loop
Create your own range function
Practical example to use iterator


In [2]:
import numpy as np

In [3]:
p = [[1, 5],
 [3, 7],
 [4, 9]]

In [4]:
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

In [10]:
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [11]:
arr1 = np.array([[7, 13, 14],

[18, 10, 17],

[11, 12, 19]])

In [12]:
arr2 = np.array([16, 6, 1])

In [20]:
arr3 = np.array([[5, 8, 4, 3]])
arr3

array([[5, 8, 4, 3]])

In [22]:
arr3.reshape((4,1))

array([[5],
       [8],
       [4],
       [3]])

In [ ]:
arr3 = np.array([[5], [8], [4], [3]])
arr3

In [14]:
arr4 = np.vstack((arr1, arr2))
arr4

array([[ 7, 13, 14],
       [18, 10, 17],
       [11, 12, 19],
       [16,  6,  1]])

In [19]:
arr5 = np.hstack((arr4, arr3))
arr5

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

In [23]:
# Read the input
list_1 = [[7, 13, 14],[18, 10, 17],[11, 12, 19]]
list_2 = [16, 6, 1]
list_3 = [[5, 8, 4, 3]]

# Import NumPy
import numpy as np

# Write your code here
np_list_1 = np.array(list_1)
np_list_2 = np.array(list_2)
np_list_3 = np.array(list_3).reshape((4,1))
list_1_2 =  np.vstack((np_list_1, np_list_2))
final_array = np.hstack((list_1_2, np_list_3))
print(final_array)


[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [24]:
# Read the input
list_1 = [[7, 13, 14],[18, 10, 17],[11, 12, 19]]
list_2 = [16, 6, 1]
list_3 = [[5, 8, 4, 3]]

# Import NumPy
import numpy as np

# Write your code here
final_array = np.hstack((np.vstack((np.array(list_1), np.array(list_2))), np.array(list_3).reshape((4,1))))
print(final_array)


[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv', sep='|', header=None)
df

0        1            2   3   4   5
0    1   Akshay  Mathematics  50  40  80
1    2   Mahima      English  40  33  83
2    3    Vikas  Mathematics  50  42  84
3    4  Abhinav      English  40  31  78
4    5   Mahima      Science  50  40  80
5    6   Akshay      Science  50  49  98
6    7  Abhinav  Mathematics  50  47  94
7    8    Vikas      Science  50  40  80
8    9  Abhinav      Science  50  47  94
9   10    Vikas      English  40  39  98
10  11   Akshay      English  40  35  88
11  12   Mahima  Mathematics  50  43  86

In [8]:
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv', sep='|')

df.head()

1   Akshay  Mathematics  50  40  80
0  2   Mahima      English  40  33  83
1  3    Vikas  Mathematics  50  42  84
2  4  Abhinav      English  40  31  78
3  5   Mahima      Science  50  40  80
4  6   Akshay      Science  50  49  98

In [19]:
columts = ['S.No.', 'Name', 'Subject', 'Maximum Marks', 'Marks Obtained', 'Percentage']
df = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv", sep='|', names=columts, index_col=['S.No.'])
# df.set_index('S.No.', inplace=True)
df

Name      Subject  Maximum Marks  Marks Obtained  Percentage
S.No.                                                                 
1       Akshay  Mathematics             50              40          80
2       Mahima      English             40              33          83
3        Vikas  Mathematics             50              42          84
4      Abhinav      English             40              31          78
5       Mahima      Science             50              40          80
6       Akshay      Science             50              49          98
7      Abhinav  Mathematics             50              47          94
8        Vikas      Science             50              40          80
9      Abhinav      Science             50              47          94
10       Vikas      English             40              39          98
11      Akshay      English             40              35          88
12      Mahima  Mathematics             50              43          86

: 